[package]
name = "dao-governance"
version = "0.1.0"
edition = "2024"

[lib]
name = "governance"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
